version: "3"
services:
  nginx:
    image: nginx:1.25.2
    ports:
      - "8080:80"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./njs:/etc/nginx/njs
      - ./storage:/etc/nginx/storage
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./template-variables:/etc/nginx/templates/10-variables.conf.template:ro
    environment:
      - COUPLE_PAGE=maya-enggar-2
      - UPSTREAM_DOMAIN=zivisual.net
      - UPSTREAM_ENABLE_SSL=true
      - ENABLE_SSL=false
      - DOMAIN=localhost:8080
      - ENABLE_WEBDIS=true
      - WEBDIS_URL=http://webdis:7379
  redis:
    image: redis:6.2.5
    ports:
      - "6379"
  webdis:
    image: nicolas/webdis:0.1.22
    ports:
      - "7379:7379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./webdis.json:/etc/webdis.prod.json
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
