version: "3"
services:
  nginx:
    image: nginx:1.25.2
    ports:
      - "8080:80"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./njs:/etc/nginx/njs
      - ./storage:/etc/nginx/storage
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./template-variables:/etc/nginx/templates/10-variables.conf.template:ro
    environment:
      - COUPLE_PAGE=maya-enggar-2
      - UPSTREAM_DOMAIN=https://zivisual.net
