version: "3"
services:
  nginx:
    image: bintangbahy/nginx-njs-learn:latest
    ports:
      - "8080:80"
    environment:
      - COUPLE_PAGE=maya-enggar-2
      - UPSTREAM_DOMAIN=zivisual.net
      - UPSTREAM_ENABLE_SSL=true
      - ENABLE_SSL=true
      - DOMAIN=localhost:8080
